version: '3'

services:
  app:
    build: ./docker/php
    depends_on:
      - database
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - 3000:80
      
  database:
    build: ./docker/database
    volumes:
      - ./docker/database/data:/var/lib/mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
